require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/rvm"
require "capistrano/bundler"
require "capistrano/rails/assets"
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
#require "capistrano/delayed-job"
Dir.glob("lib/capistrano/tasks/*.cap").map &:import
