require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/rvm"
require "capistrano/npm"
require "capistrano/rails"
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
#require "capistrano/delayed-job"
Dir.glob("lib/capistrano/tasks/*.cap").map &:import
